### ISSUE TITLE
suspicious size of data

### ISSUE THREAD

**Issue by jonjab** [ucsb-dreamlab/dianpingBusinessScrape#2]
I think we are getting the first page of results for each city. 
Every file I check has 16 libraries.

**Comment by Jinxiang2000** [comment]
Thanks for your feedback!! Unfortunately, as visitors, we only see the first page of results for each city; to view additional pages, we must have a dianping account.  I tried to register a dianping account, but I was getting blocked because I couldn't create an account using a US phone number.

**Comment by jonjab** [comment]
Thanks! 

This reminds me that you mentioned it along the way. 

80 * 16 = 7200. hat's already WAY more than 10 years ago!
